from lib.build_systems.autotools import AutotoolsPackage


class Vcftools(AutotoolsPackage):
    """VCFtools is a program package designed for working with VCF files,
    such as those generated by the 1000 Genomes Project. The aim of
    VCFtools is to provide easily accessible methods for working
    with complex genetic variation data in the form of VCF files.
    """

    homepage = "https://vcftools.github.io/"
    url = "https://github.com/vcftools/vcftools/releases/download/v{version}/vcftools-{version}.tar.gz"

    versions = [
        "0.1.16",
    ]
