from lib.build_systems.binary import BinaryPackage


class Transdecoder(BinaryPackage):
    """TransDecoder identifies candidate coding regions within transcript
    sequences, such as those generated by de novo RNA-Seq transcript
    assembly using Trinity, or constructed based on RNA-Seq alignments to
    the genome using Tophat and Cufflinks."""

    homepage = "https://transdecoder.github.io/"
    url = "https://github.com/TransDecoder/TransDecoder/archive/TransDecoder-v{version}.tar.gz"

    versions = [
        "5.7.1",
    ]
