import shutil
from lib.dependency import Dependency
from lib.package import Package


class Ninja(Package):
    """Ninja is a small build system with a focus on speed. It differs from
    other build systems in two major respects: it is designed to have its input
    files generated by a higher-level build system, and it is designed to run
    builds as fast as possible."""

    homepage = "https://ninja-build.org/"
    url = "https://github.com/ninja-build/ninja/archive/v{version}.tar.gz"

    versions = [
        "1.13.0",
    ]

    depends_on = [
        Dependency("python", type="build"),
    ]

    def build(self):
        self.run_cmd(["python", "configure.py", "--bootstrap"], cwd=self.build_dir)

    def install(self):
        bin_dir = self.prefix / "bin"
        bin_dir.mkdir(parents=True, exist_ok=True)

        shutil.copy2(self.build_dir / "ninja", bin_dir / "ninja")
